conectando a uma pasta no drive

In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

importando as bibliotecas nessesarias 

In [6]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

ModuleNotFoundError: No module named 'sklearn'

carregando os dados exemplo


caregando os dados pratica 

In [ ]:
# lendo dados do csv para um data frame
# df = pd.read_csv('/content/drive/MyDrive/db.csv')
df = pd.read_csv('/db.csv')
# display(df)

In [ ]:
df.isnull().any()

ano               False
densidade         False
id_municipio      False
sigla_uf          False
taxa_aprovacao    False
dtype: bool

In [ ]:
# df = df.where(df['densidade'] != np.NAN)
# df = df.where(df['taxa_aprovacao'] != np.NAN)
# df = df.where(df['densidade'] != np.Infinity)
# df = df.where(df['taxa_aprovacao'] != np.Infinity)


In [ ]:
y = df['taxa_aprovacao']
X = df['densidade']

In [ ]:
print(y)
print(X)

In [ ]:
# transformX = Normalizer().fit([X])
# transformY = Normalizer().fit([y])
# display(transformX)
# display(transformY)

In [ ]:
X = Normalizer().fit([X]).transform([X])
y = Normalizer().fit([y]).transform([y])

In [ ]:
# display(X.reshape(-1,1))
display(X)
display(y)

array([[2.66591242e-03],
       [8.45694494e-05],
       [4.29835588e-05],
       ...,
       [2.13408222e-03],
       [5.82186315e-03],
       [5.50534907e-03]])

array([[0.00250734, 0.0027772 , 0.00289506, ..., 0.00576068, 0.00576068,
        0.00576068]])

Selecionando Variáveis para o modelo


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X.reshape(-1,1), y.reshape(-1,1), test_size=0.25)


In [ ]:
display(X_train, X_test, y_train, y_test)

array([[0.000326  ],
       [0.00954806],
       [0.00111155],
       ...,
       [0.00040721],
       [0.01275175],
       [0.00106994]])

array([[3.07216874e-03],
       [1.40578875e-02],
       [1.67718252e-02],
       ...,
       [9.69200062e-05],
       [2.87572235e-03],
       [1.50189860e-02]])

array([[0.0055725 ],
       [0.00507502],
       [0.00540928],
       ...,
       [0.0040463 ],
       [0.00551724],
       [0.00464887]])

array([[0.00546593],
       [0.00460323],
       [0.00542323],
       ...,
       [0.00469983],
       [0.00539328],
       [0.00508284]])

In [ ]:
# Criando o modelo LinearRegression
regr = LinearRegression()

In [ ]:
regr.fit(X, y)

NameError: ignored

In [ ]:
# Realizar treinamento do modelo
regr.fit(X, y)
regr.fit(X_train, y_train)

In [ ]:

# Realizar predição com os dados separados para teste
y_pred = lr.predict(X_test)
# Visualização dos 20 primeiros resultados
y_pred[:20]